### ISSUE TITLE
zeroconf separate network problem

### ISSUE THREAD

**Issue by andrejpan** [fkie/multimaster_fkie#38]
Hey,

I am using Ubuntu 14.04 and Indigo ROS on Intel based pc (hostname atbeetz5). I run separately roscore and node_manager. Faculty IT department updated firmware on the network switches and master_discovery is not working anymore. With zeroconf discovery I also have problems, because I can not have separate network for my project. 

I establish connection like this:
![zeroconf1](https://cloud.githubusercontent.com/assets/1015265/16522870/9cf48a4e-3fa0-11e6-9abc-6a9f16534e53.png)
  
But I can immediately see other nodes and topics which should be in the network 0.
![zeroconf2](https://cloud.githubusercontent.com/assets/1015265/16523146/21acb760-3fa2-11e6-9d06-ef013453e2f8.png)
  

Any idea what I am doing wrong or this could be a bug?

**Comment by atiderko** [comment]
Hi @andrejpan,

`zeroconf disocvery` does not support network separation in the current implementation. I will try to add this feature in the next time. In the meantime you can try to use `master_discovery` and add hosts to discover in  `Robot hosts` parameter. This hosts are then `pinged` using unicast communication. I think your multicast communication is blocked since the firmware update of your switches.

**Comment by andrejpan** [comment]
Hey, 
thank you for informations. Did I missed somewhere that `zeroconf disocvery` does not support network separation? Blocking an input of a network number parameter would be nice or short massage around the input when discovery type selection is changed. 

I found out that I must put two IP addresses inside `Robot hosts` parameter (one from PC which runs node_manager and one from PC that I want to add new ROS node). 

On LAN wiring `master_discovery` works, but wifi setting are a bit broken and apparently I can just wait for new update.

**Comment by atiderko** [comment]
Hi,

you are right, it seems to be uncommented feature.

It's strange that you need to define two addresses. What happens if you put only the address of the remote host?

What is about wifi? Is it not configured? Or does it not work with `master_discovery`?

**Comment by andrejpan** [comment]
If I only put an address of remote host I do not see remote host at node_manager. 
Remote host:
```
pixuser@pixdrone1:~$ rostopic echo /master_discovery/changes 
state: 'changed'
master: 
  name: pixdrone1
  uri: http://pixdrone1:11311/
  timestamp: 1467704163.24
  timestamp_local: 1467704163.24
  online: True
  discoverer_name: /master_discovery
  monitoruri: http://172.24.16.156:11611
---
pixuser@pixdrone1:~$ rostopic echo /master_discovery/linkstats 
header: 
  seq: 1
  stamp: 
    secs: 1467704186
    nsecs: 496687889
  frame_id: pixdrone1
links: 
  - 
    destination: pixdrone1
    quality: 100.0
---
```
Local host:
```
pangerca@atbeetz5:~$ rostopic echo /master_discovery/changes 
state: 'changed'
master: 
  name: atbeetz5
  uri: http://atbeetz5:11311/
  timestamp: 1467705390.97
  timestamp_local: 1467705390.97
  online: True
  discoverer_name: /master_discovery
  monitoruri: http://172.24.16.36:11611
---
pangerca@atbeetz5:~$ rostopic echo /master_discovery/linkstats 
header: 
  seq: 129
  stamp: 
    secs: 1467705406
    nsecs: 542614936
  frame_id: atbeetz5
links: 
  - 
    destination: atbeetz5
    quality: 100.0
---
```

When I put both ip addresses I see this:
```
pixuser@pixdrone1:~$ rostopic echo /master_discovery/changes 
state: 'changed'
master: 
  name: pixdrone1
  uri: http://pixdrone1:11311/
  timestamp: 1467704299.91
  timestamp_local: 1467704299.91
  online: True
  discoverer_name: /master_discovery
  monitoruri: http://172.24.16.156:11611
---
pixuser@pixdrone1:~$ rostopic echo /master_discovery/linkstats 
header: 
  seq: 1
  stamp: 
    secs: 1467704321
    nsecs: 522756099
  frame_id: pixdrone1
links: 
  - 
    destination: pixdrone1
    quality: 100.0
  - 
    destination: atbeetz5
    quality: 100.0
---
```
and local host:
```
pangerca@atbeetz5:~$ rostopic echo /master_discovery/changes 
state: 'changed'
master: 
  name: atbeetz5
  uri: http://atbeetz5:11311/
  timestamp: 1467706420.22
  timestamp_local: 1467706420.22
  online: True
  discoverer_name: /master_discovery
  monitoruri: http://172.24.16.36:11611
---
pangerca@atbeetz5:~$ rostopic echo /master_discovery/linkstats 
header: 
  seq: 1015
  stamp: 
    secs: 1467706294
    nsecs: 578988075
  frame_id: atbeetz5
links: 
  - 
    destination: atbeetz5
    quality: 100.0
---
```

Network is faculty(TUM informatics) based and we have a virtual network on this infrastructure. `master_discovery` apparently was working until they updated wifi firmware some months ago (that's how people told me). Is there a tool that I could get all the parameters of the network and see what could be wrong? Otherwise I tested udp multicast with these two commands and nothing came through.
```
iperf -s -u -B 226.0.0.0 -i 1
iperf -c 226.0.0.0 -u -T 32 -t 3 -i 1
```
